version: '3'
services:
  auditbeat:
    container_name: auditbeat 
    user: root #To read the docker socket
    image: docker.elastic.co/beats/auditbeat:7.6.2
    volumes:
     #Mount the Auditbeat configuration so users can make edits.
     - /opt/threathunt/auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml
     #Allows us to report on docker from the hosts information.
     - /var/run/docker.sock:/var/run/docker.sock
    pid: host # Set the required permissions with pid and cap_add for Auditbeat
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    networks: 
     - elastic
    command: auditbeat -e --strict.perms=false
    restart: unless-stopped
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge
